steps:
- name: 'ubuntu'
  args: ['echo', 'trigger1']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  dir: 'trigger1'
  args:
   - '-c'
   - |
     gcloud functions deploy replicate-data \
     --region=us-central1 \
     --trigger-http \
     --entry-point=main.hello_world \
     --runtime=python38

